### ISSUE TITLE
Multiple definition of `g_ecall_table', `g_dyn_entry_table' ..

### ISSUE THREAD

**Issue by khanhct-viosoft** [bl4ck5un/mbedtls-SGX#10]
Hi Mbedtls.
I got issues  when I add libmbedtls_SGX_t.a and libmbedtls_SGX_u.a to my project 

`[100%] Linking CXX shared library libeu4_crypto_enclave.so
../../enclave/libs/mbedtls_sgx/libmbedtls_SGX_t.a(mbedtls_SGX_t.c.o):(.data.rel.ro.local+0x0): multiple definition of `g_ecall_table'
CMakeFiles/Enclave_t.dir/Enclave_t.c.o:(.data.rel.ro.local+0x0): first defined here
/usr/bin/ld: Warning: size of symbol `g_ecall_table' changed from 648 in CMakeFiles/Enclave_t.dir/Enclave_t.c.o to 24 in ../../enclave/libs/mbedtls_sgx/libmbedtls_SGX_t.a(mbedtls_SGX_t.c.o)
../../enclave/libs/mbedtls_sgx/libmbedtls_SGX_t.a(mbedtls_SGX_t.c.o): In function `sgx_dummy':
/eu4dev/mbedtls-SGX/trusted/mbedtls_SGX_t.c:92: multiple definition of `g_dyn_entry_table'
CMakeFiles/Enclave_t.dir/Enclave_t.c.o:(.rodata+0x0): first defined here
/usr/bin/ld: Warning: size of symbol `g_dyn_entry_table' changed from 488 in CMakeFiles/Enclave_t.dir/Enclave_t.c.o to 24 in ../../enclave/libs/mbedtls_sgx/libmbedtls_SGX_t.a(mbedtls_SGX_t.c.o)
collect2: error: ld returned 1 exit status
enclave/CMakeFiles/eu4_crypto_enclave.dir/build.make:123: recipe for target 'enclave/libeu4_crypto_enclave.so' failed
make[2]: *** [enclave/libeu4_crypto_enclave.so] Error 1
CMakeFiles/Makefile2:250: recipe for target 'enclave/CMakeFiles/eu4_crypto_enclave.dir/all' failed
`
------------------------------------------------------------------------------------------------------------
CMakefile

`set(MBEDTLS_SGX_LIBRARY_DIR ${CMAKE_CURRENT_SOURCE_DIR}/libs/mbedtls_sgx)
set(MBEDTLS_SGX_LIB_T ${MBEDTLS_SGX_LIBRARY_DIR}/libmbedtls_SGX_t.a)

target_link_libraries(${UE4_PROJECT_NAME}_enclave
	"-Wl,--whole-archive"
	${Trts_Library_Name}
	"-Wl,--no-whole-archive"
	"-Wl,--start-group"
	${MBEDTLS_SGX_LIB_T}
	"sgx_tstdc"
	"sgx_tcxx"
	"${Crypto_Library_Name}"
	"${Service_Library_Name}"
	"-Wl,--end-group"
	"-Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie,-eenclave_entry -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0 -Wl,--gc-sections -Wl,--version-script=${version_script_file}"
)
`
Please help me to fix this issue. 
Thanks!

**Comment by bl4ck5un** [comment]
There can be many reasons leading to the redefinition of symbols. It's hard to tell by just reading that part of the makefile. But it's unlikely to be an issue with the library, as symbols in question `g_ecall_table` are generated by SGX `edge8r`. Is mbedlts-SGX.edl included in your main EDL?

**Comment by khanhct-viosoft** [comment]
Is mbedlts-SGX.edl included in your main EDL?
Thanks! I forget that. It worked.
